name: iOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, macOS, ARM64]

    steps:
      - uses: actions/checkout@v4

      - name: Build IPA
        run: ./scripts/deployment/ios/build-ipa.sh
