name: Unit Test

on:
  workflow_call:

jobs:
  run:
    runs-on: [self-hosted, g3-runner]

    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "/opt/homebrew/bin:/opt/homebrew/opt/ruby/bin" >> $GITHUB_PATH

      - run: |
          chmod +x scripts/deployment/common/run-unit-tests.sh
          scripts/deployment/common/run-unit-tests.sh $GITHUB_WORKSPACE
