import { MD3DarkTheme, MD3LightTheme } from 'react-native-paper';
import { AppThemeType } from 'src/core/type/ThemeType';

export const AppLightTheme: AppThemeType = {
    ...MD3LightTheme,
    colors: {
        ...MD3DarkTheme.colors,
        label_surface_button_light: '#f0f0f0',
        label_surface_button_off: '#c8c8c8',
        label_surface_button_pressed: '#000000',
        label_surface_button_primary: '#e1251b',
        label_surface_disable: '#cfc2c6',
        label_text_disable: '#ffffff',
        outline_outine: '#f0f0f0',
        outline_outine_lightest: '#f8f8f8',
        outline_outine_brands: '#e1251b',
        outline_outine_brands_off: '#b78f8d',
        outline_outine_medium: '#c8c8c8',
        outline_outine_strong: '#272727',
        success_container: '#e8fff0',
        success_outline: '#8dface',
        success_text: '#4ca977',
        surface_surface__medium: '#f0f0f0',
        surface_surface_brand: '#e1251b',
        surface_surface_brand_light: '#ffdeda',
        surface_surface_brand_lightest: '#fff4f4',
        surface_surface_nav: '#ffffffcc',
        surface_surface_nav_2: '#f9d5d3',
        surface_surface_button_container: '#ffffff14',
        surface_surface_default: '#f8f8f8',
        surface_surface_high: '#ffffff',
        text_on_surface_text_brand: '#ffffff',
        text_on_surface_text_brand_2: '#e1251b',
        text_on_surface_text_high: '#272727',
        text_on_surface_text_highest: '#000000',
        text_on_surface_text_invert: '#ffffff',
        text_on_surface_text_light: '#a6a9b0',
        text_on_surface_text_lightest: '#c8c8c8',
        text_on_surface_text_medium: '#6c6f73',
        text_on_surface_text_medium_high: '#3e3f40',
        warning_container: '#fff8eb',
        warning_outline: '#ffe58f',
        warning_text: '#ffb625',
    },
};

export const AppDarkTheme: AppThemeType = {
    ...MD3DarkTheme,
    colors: {
        ...MD3DarkTheme.colors,
        label_surface_button_light: '#3E3F40',
        label_surface_button_off: '#3e3f40',
        label_surface_button_pressed: '#6c6f73',
        label_surface_button_primary: '#e5382e',
        label_surface_disable: '#3e3f40',
        label_text_disable: '#6c6f73',
        outline_outine: '#3e3f40',
        outline_outine_lightest: '#3e3f40',
        outline_outine_brands: '#e1251b',
        outline_outine_brands_off: '#826867',
        outline_outine_medium: '#6c6f73',
        outline_outine_strong: '#f8f8f8',
        success_outline: '#8dface',
        success_text: '#4ca977',
        surface_surface__medium: '#3e3f40',
        surface_surface_brand: '#e5382e',
        surface_surface_brand_light: '#ffdeda',
        surface_surface_brand_lightest: '#ffdeda',
        surface_surface_nav: '#000000cc',
        surface_surface_button_container: '#00000014',
        surface_surface_default: '#171717',
        surface_surface_high: '#272727',
        text_on_surface_text_brand: '#ffffff',
        text_on_surface_text_brand_2: '#e5382e',
        text_on_surface_text_high: '#f8f8f8',
        text_on_surface_text_highest: '#ffffff',
        text_on_surface_text_invert: '#ffffff',
        text_on_surface_text_light: '#a6a9b0',
        text_on_surface_text_lightest: '#6c6f73',
        text_on_surface_text_medium: '#c8c8c8',
        text_on_surface_text_medium_high: '#f0f0f0',
        warning_container: '#ffb6251a',
        warning_outline: '#ffe58f',
        warning_text: '#ffb625',
        surface_surface_nav_2: '#f9d5d3',
    },
};
