import * as Config from '../../../env.config';

export default {
  ENV_NAME: process.env.ENV_NAME ?? Config.ENV_NAME,
  TON_VIEWER_URL: process.env.TON_VIEWER_URL ?? Config.TON_VIEWER_URL,
  BASE_URL: process.env.BASE_URL ?? Config.BASE_URL,
  ENV: process.env.ENV ?? Config.ENV,
  BLOCK_CYPHER_TOKEN: process.env.BLOCK_CYPHER_TOKEN ?? Config.BLOCK_CYPHER_TOKEN,
  BLOCK_CYPHER_BTC_DATA_ULR: process.env.BLOCK_CYPHER_BTC_DATA_ULR ?? Config.BLOCK_CYPHER_BTC_DATA_ULR,
  BLOCK_CYPHER_PUSH_TRANSACTION_ULR:
    process.env.BLOCK_CYPHER_PUSH_TRANSACTION_ULR ?? Config.BLOCK_CYPHER_PUSH_TRANSACTION_ULR,
  BLOCK_CYPHER_PUSH_TRANSACTION_DETAIL_ULR:
    process.env.BLOCK_CYPHER_PUSH_TRANSACTION_DETAIL_ULR ?? Config.BLOCK_CYPHER_PUSH_TRANSACTION_DETAIL_ULR,
  BLOCK_CYPHER_ADDRESS_ULR: process.env.BLOCK_CYPHER_ADDRESS_ULR ?? Config.BLOCK_CYPHER_ADDRESS_ULR,
  ADMIN_ADDRESS: process.env.ADMIN_ADDRESS ?? Config.ADMIN_ADDRESS,
  ADMIN_FEE_PERCENT: (process.env.ADMIN_FEE_PERCENT ? parseFloat(process.env.ADMIN_FEE_PERCENT) : Config.ADMIN_FEE_PERCENT) as any,
  TON_API_TOKEN: process.env.TON_API_TOKEN ?? Config.TON_API_TOKEN,
  TON_API_BASE_URL: process.env.TON_API_BASE_URL ?? Config.TON_API_BASE_URL,
  ADMIN_TON_ADDRESS: process.env.ADMIN_TON_ADDRESS ?? Config.ADMIN_TON_ADDRESS,
  EMAIL_SUPPORT: process.env.EMAIL_SUPPORT ?? "",
  TON_VIEWER_TRANSACTION_URL: process.env.TON_VIEWER_TRANSACTION_URL ?? Config.TON_VIEWER_TRANSACTION_URL,
  BNB_EXPLORER_URL: process.env.BNB_EXPLORER_URL ?? Config.BNB_EXPLORER_URL,
  ETH_EXPLORER_URL: process.env.ETH_EXPLORER_URL ?? Config.ETH_EXPLORER_URL,
  POL_EXPLORER_URL: process.env.POL_EXPLORER_URL ?? Config.POL_EXPLORER_URL,
  API_KEY: process.env.API_KEY ?? Config.API_KEY,
  MORALIS_URL: process.env.MORALIS_URL ?? Config.MORALIS_URL,
  MORALIS_API_KEY: process.env.MORALIS_API_KEY ?? Config.MORALIS_API_KEY,
  TON_NON_BOUNCEABLE_MESSAGE_URL:
    process.env.TON_NON_BOUNCEABLE_MESSAGE_URL ?? Config.TON_NON_BOUNCEABLE_MESSAGE_URL,
  AUTH0_CALLBACK_URL_ANDROID: process.env.AUTH0_CALLBACK_URL_ANDROID ?? "",
  AUTH0_CALLBACK_URL_IOS: process.env.AUTH0_CALLBACK_URL_IOS ?? "",
  AUTH0_CLIENT_ID: process.env.AUTH0_CLIENT_ID ?? Config.WALLET_CONNECT_PROJECT_ID, // fallback to project id if needed
  AUTH0_DOMAIN: process.env.AUTH0_DOMAIN ?? "",
  AUTH0_AUDIENCE: process.env.AUTH0_AUDIENCE ?? "",
  REZ_POINT_HOME: process.env.REZ_POINT_HOME ?? "",
  REZ_POINT_PACKAGE: process.env.REZ_POINT_PACKAGE ?? "",
  CHANGE_NOW_BASE_URL: process.env.CHANGE_NOW_BASE_URL ?? Config.CHANGE_NOW_BASE_URL,
  CHANGE_NOW_API_KEY: process.env.CHANGE_NOW_API_KEY ?? Config.CHANGE_NOW_API_KEY,
  CHANGE_NOW_PARTNER_KEY: process.env.CHANGE_NOW_PARTNER_KEY ?? Config.CHANGE_NOW_PARTNER_KEY,
  PINATA_API_KEY: process.env.PINATA_API_KEY ?? Config.PINATA_API_KEY,
  PINATA_API_SECRET: process.env.PINATA_API_SECRET ?? Config.PINATA_API_SECRET,
  TON_API_KEY: process.env.TON_API_KEY ?? Config.TON_API_KEY,
};
