import { useNavigation, useRoute } from '@react-navigation/native';
import { BlurView } from 'expo-blur';
import React from 'react';
import {
    Image,
    SafeAreaView,
    Text,
    TouchableOpacity,
    View,
} from 'react-native';
import AIDetailStyle from './AIDetail.style';

import BackIcon from 'src/assets/icons/arrow_left.svg';
import ExportIcon from 'src/assets/icons/new_send.svg';
import HeartIcon from 'src/assets/icons/star.svg';

const AIDetailScreen = () => {
    const navigation = useNavigation<any>();
    const route = useRoute<any>();
    const { imageUri, title } = route.params || {};

    const owlImage = 'https://i.ibb.co/L6V6v6V/owl.png';

    return (
        <View style={AIDetailStyle.container}>
            <Image
                source={{ uri: imageUri || owlImage }}
                style={AIDetailStyle.backgroundImage}
                resizeMode="cover"
            />

            <SafeAreaView style={{ flex: 1 }}>
                <View style={AIDetailStyle.header}>
                    <TouchableOpacity onPress={() => navigation.goBack()}>
                        <BackIcon width={24} height={24} fill="#fff" />
                    </TouchableOpacity>
                    <Text style={AIDetailStyle.headerTitle}>AI360</Text>
                    <View style={{ width: 24 }} />
                </View>

                {/* Social Actions */}
                <View style={AIDetailStyle.socialActions}>
                    <TouchableOpacity style={AIDetailStyle.likeBadge}>
                        <HeartIcon width={16} height={16} fill="#fff" />
                        <Text style={AIDetailStyle.likeText}>2.3k</Text>
                    </TouchableOpacity>

                    <TouchableOpacity style={[AIDetailStyle.socialIcon, { backgroundColor: '#E60023' }]}>
                        {/* Pinterest Placeholder */}
                        <Text style={{ color: '#fff', fontWeight: 'bold' }}>P</Text>
                    </TouchableOpacity>

                    <TouchableOpacity style={[AIDetailStyle.socialIcon, { backgroundColor: '#0057FF' }]}>
                        {/* Behance Placeholder */}
                        <Text style={{ color: '#fff', fontWeight: 'bold' }}>Bē</Text>
                    </TouchableOpacity>

                    <TouchableOpacity style={AIDetailStyle.socialIcon}>
                        <ExportIcon width={20} height={20} fill="#fff" />
                    </TouchableOpacity>
                </View>

                {/* Info Card */}
                <View style={AIDetailStyle.infoCard}>
                    <BlurView intensity={80} style={AIDetailStyle.blurContainer} tint="dark">
                        <Text style={AIDetailStyle.title}>{title || 'A lovely blue owl'}</Text>

                        <View style={AIDetailStyle.statsRow}>
                            <View>
                                <Text style={AIDetailStyle.label}>Licenses</Text>
                                <Text style={AIDetailStyle.value}>Free use</Text>
                            </View>
                            <View style={{ alignItems: 'flex-end' }}>
                                <Text style={AIDetailStyle.label}>Generated by</Text>
                                <View style={AIDetailStyle.creatorInfo}>
                                    <Text style={AIDetailStyle.creatorName}>AIG Robot</Text>
                                    <Image
                                        source={{ uri: 'https://i.ibb.co/XzVzVzV/avatar.png' }}
                                        style={AIDetailStyle.creatorAvatar}
                                    />
                                </View>
                            </View>
                        </View>

                        <View style={AIDetailStyle.buttonRow}>
                            <TouchableOpacity style={AIDetailStyle.donateButton}>
                                <Text style={AIDetailStyle.donateText}>Donate</Text>
                            </TouchableOpacity>
                            <TouchableOpacity style={AIDetailStyle.downloadButton}>
                                <Text style={AIDetailStyle.downloadText}>Download</Text>
                            </TouchableOpacity>
                        </View>
                    </BlurView>
                </View>
            </SafeAreaView>
        </View>
    );
};

export default AIDetailScreen;
