enum NavigationStackKey {
  AuthStack = "AuthStack",
  HomeStack = "HomeStack",
  CreateWalletStack = "CreateWalletStack",
  RestoreWalletStack = "RestoreWalletStack",
  PinCodeStack = "PinCodeStack",
  CongratulationCreateWallet = "CongratulationCreateWallet",
}

enum AuthStackScreenKey {
  SplashScreen = "SplashScreen",
  OnboardingScreen = "OnboardingScreen",
  ShowPassPhrase = "ShowPassPhrase",
  ValidatePassPhrase = "ValidatePassPhrase",
  SocialAuthScreen = "SocialAuthScreen",
  CreateNewWallet = "CreateNewWallet",
  RePinCode = "RePinCode",
  CongratulationCreateWallet = "CongratulationCreateWallet",
}

enum HomeStackScreenKey {
  Send = "Send",
  Transfer = "Transfer",
  BottomTab = "BottomTab",
  Bitcoin = "Bitcoin",
  ChatScreen = "ChatScreen",
  Ton = "Ton",
  Jetton = "Jetton",
  TransactionDetails = "TransactionDetails",
  Setting = "Setting",
  AboutUs = "AboutUs",
  Contact = "Contact",
  FAQ = "FAQ",
  AboutUsDetail = "AboutUsDetail",
  ContactSuccess = "ContactSuccess",
  FAQDetail = "FAQDetail",
  Receive = "Receive",
  SelectToken = "SelectToken",
  RecoveryPhrase = "RecoveryPhrase",
  ManageCrypto = "ManageCrypto",
  Currency = "Currency",
  ChangeLanguage = "ChangeLanguage",
  ChangePincode = "ChangePincode",
  NFTDetail = "NFTDetail",
  NFTList = "NFTList",
  NFTImport = "NFTImport",
  NFTSend = "NFTSend",
  NFTConfirmationSend = "NFTConfirmationSend",
  NotificationList = "NotificationList",
  NotificationDetail = "NotificationDetail",
  ProjectDetail = "ProjectDetail",
  AddProtocol = "AddProtocol",
  AddCustomToken = "AddCustomToken",
  SelectTokenEVM = "SelectTokenEVM",
  ConfirmClaimToken = "ConfirmClaimToken",
  PriceFeedList = "PriceFeedList",
  NFTYouOwnList = "NFTYouOwnList",
  TransactionClaimDetail = "TransactionClaimDetail",
  TransactionProjectDetails = "TransactionProjectDetails",
  TokenDetailEVM = "TokenDetailEVM",
  ClaimDetailList = "ClaimDetailList",
  NFTCollectionStats = "NFTCollectionStats",
  NFTUnAddedDetail = "NFTUnAddedDetail",

  NFTTonDetail = "NFTTonDetail",
  NFTTonList = "NFTTonList",
  NFTTonImport = "NFTTonImport",
  NFTTonSend = "NFTTonSend",
  NFTTonSendDetail = "NFTTonSendDetail",
  NFTTonConfirmationSend = "NFTTonConfirmationSend",
  Top10EVMs = "Top10EVMs",
  Top10Tokens = "Top10Tokens",
  Swap = "SwapCurrency",
  TransactionHistorySwapDetail = "TransactionHistorySwapDetail",
  GuidingSwap = "GuidingSwap",
  ScanScreen = "ScanScreen",
  DAppBrowserScreen = "DAppBrowserScreen",
  ConnectionScreen = "ConnectionScreen",
  BrowseScreen = "BrowseScreen",
  Scan = "Scan",
  ScanEvm = "ScanEvm",
  MintNftScreen = "MintNftScreen",
  MoreActionScreen = "MoreActionScreen",
  NFTMarketplace = "NFTMarketplace",
  NFTCollection = "NFTCollection",
  AIDetailScreen = "AIDetailScreen",
  NFTMarketplaceCollectionDetail = "NFTMarketplaceCollectionDetail",
  DepositOptions = "DepositOptions",
  P2PMarket = "P2PMarket",
  P2PBuyDetail = "P2PBuyDetail",
  P2POrderDetails = "P2POrderDetails",
  Trading = "Trading",
  TradingDetail = "TradingDetail",
  Offerwall = "Offerwall",
  FeedScreen = "FeedScreen",
  LiveBroadcastScreen = "LiveBroadcastScreen",
  LiveViewerScreen = "LiveViewerScreen",
  SocialProfileScreen = "SocialProfileScreen",
  CreatePostScreen = "CreatePostScreen",
  PostDetailScreen = "PostDetailScreen",
  MarketplaceHomeScreen = "MarketplaceHomeScreen",
  ConnectWalletScreen = "ConnectWalletScreen",
  CreateNFTScreen = "CreateNFTScreen",
  MyNFTsScreen = "MyNFTsScreen",
  NFTDetailScreen = "NFTDetailScreen",
  CreateAuctionScreen = "CreateAuctionScreen",
  AuctionDetailScreen = "AuctionDetailScreen",
  BidHistoryScreen = "BidHistoryScreen",

  // Ticket Wallet Platform
  TicketWallet = "TicketWallet",
  TicketDetail = "TicketDetail",
  TicketQR = "TicketQR",
  TicketTransfer = "TicketTransfer",
  TicketScanner = "TicketScanner",
}

enum CreateWalletStackScreenKey {
  RecoveryPhraseWarning = "RecoveryPhraseWarning",
  SecretPhrase = "SecretPhrase",
  ConfirmSecretPhrase = "ConfirmSecretPhrase",
}
enum PinCodeStackScreenKey {
  CreatePin = "CreatePin",
  ReEnterPin = "ReEnterPin",
}
enum RestoreWalletStackScreenKey {
  RestoreWallet = "RestoreWallet",
}

enum BottomTabScreenKey {
  Crypto = "Crypto",
  NFTCollection = "NFT Collection",
  Transaction = "Transaction",
  Explore = "Explore",
  Setting = "Setting",
}

export {
  AuthStackScreenKey,
  BottomTabScreenKey,
  CreateWalletStackScreenKey,
  HomeStackScreenKey,
  NavigationStackKey,
  PinCodeStackScreenKey,
  RestoreWalletStackScreenKey,

};
