name: Main CI

on:
  push:
    branches:
      - "**"
    tags:
      - "production-*"
      - "development-*"

jobs:
  code-quality:
    name: Code Quality
    uses: ./.github/workflows/code-quality.yml

  unit-test:
    name: Unit Test
    needs: code-quality
    uses: ./.github/workflows/unit-test.yml
