enum NavigationStackKey {
  AuthStack = "AuthStack",
  HomeStack = "HomeStack",
  CreateWalletStack = "CreateWalletStack",
  RestoreWalletStack = "RestoreWalletStack",
  PinCodeStack = "PinCodeStack",
  CongratulationCreateWallet = "CongratulationCreateWallet",
}

enum AuthStackScreenKey {
  SplashScreen = "SplashScreen",
  OnboardingScreen = "OnboardingScreen",
}

enum HomeStackScreenKey {
  Send = "Send",
  Transfer = "Transfer",
  BottomTab = "BottomTab",
  Bitcoin = "Bitcoin",
  Ton = "Ton",
  Jetton = "Jetton",
  TransactionDetails = "TransactionDetails",
  Setting = "Setting",
  AboutUs = "AboutUs",
  Contact = "Contact",
  FAQ = "FAQ",
  AboutUsDetail = "AboutUsDetail",
  ContactSuccess = "ContactSuccess",
  FAQDetail = "FAQDetail",
  Receive = "Receive",
  SelectToken = "SelectToken",
  RecoveryPhrase = "RecoveryPhrase",
  ManageCrypto = "ManageCrypto",
  Currency = "Currency",
  ChangeLanguage = "ChangeLanguage",
  ChangePincode = "ChangePincode",
  NFTDetail = "NFTDetail",
  NFTList = "NFTList",
  NFTImport = "NFTImport",
  NFTSend = "NFTSend",
  NFTConfirmationSend = "NFTConfirmationSend",
  NotificationList = "NotificationList",
  NotificationDetail = "NotificationDetail",
  ProjectDetail = "ProjectDetail",
  AddProtocol = "AddProtocol",
  AddCustomToken = "AddCustomToken",
  SelectTokenEVM = "SelectTokenEVM",
  ConfirmClaimToken = "ConfirmClaimToken",
  PriceFeedList = "PriceFeedList",
  NFTYouOwnList = "NFTYouOwnList",
  TransactionClaimDetail = "TransactionClaimDetail",
  TransactionProjectDetails = "TransactionProjectDetails",
  TokenDetailEVM = "TokenDetailEVM",
  ClaimDetailList = "ClaimDetailList",
  NFTCollectionStats = "NFTCollectionStats",
  NFTUnAddedDetail = "NFTUnAddedDetail",
  RezPointStack = "RezPointStack",
  NFTTonDetail = "NFTTonDetail",
  NFTTonList = "NFTTonList",
  NFTTonImport = "NFTTonImport",
  NFTTonSend = "NFTTonSend",
  NFTTonSendDetail = "NFTTonSendDetail",
  NFTTonConfirmationSend = "NFTTonConfirmationSend",
  Stake = "stake",
  StakingPoolDetail = "StakingPoolDetail",
  LockScreen = "LockScreen",
  StakingTransaction = "StakingTransaction",
  StakingDetail = "StakingDetail",
  Guiding = "Guiding",
  Top10EVMs = "Top10EVMs",
  Top10Tokens = "Top10Tokens",
  Swap = "SwapCurrency",
  TransactionHistorySwapDetail = "TransactionHistorySwapDetail",
  GuidingSwap = "GuidingSwap",
  ScanScreen = "ScanScreen",
  DAppBrowserScreen = "DAppBrowserScreen",
  ConnectionScreen = "ConnectionScreen",
  BrowseScreen = "BrowseScreen",
  Scan = "Scan",
  ScanEvm = "ScanEvm",
}

enum CreateWalletStackScreenKey {
  RecoveryPhraseWarning = "RecoveryPhraseWarning",
  SecretPhrase = "SecretPhrase",
  ConfirmSecretPhrase = "ConfirmSecretPhrase",
}
enum PinCodeStackScreenKey {
  CreatePin = "CreatePin",
  ReEnterPin = "ReEnterPin",
}
enum RestoreWalletStackScreenKey {
  RestoreWallet = "RestoreWallet",
}

enum BottomTabScreenKey {
  Crypto = "Crypto",
  NFTCollection = "NFT Collection",
  Transaction = "Transaction",
  Explore = "Explore",
  Setting = "Setting",
}
enum RezPointStackScreenKey {
  RezPointMainScreen = "RezPointMainScreen",
  RezPointSignIn = "RezPointSignIn",
  RezPointHistoryScreen = "RezPointHistoryScreen",
  PersonalInformation = "PersonalInformation",
  PointHistory = "PointHistory",
  AboutRezPoint = "AboutRezPoint",
  EmailVerification = "EmailVerification",
  EmailVerifiedSuccessfully = "EmailVerifiedSuccessfully",
}
export {
  AuthStackScreenKey,
  BottomTabScreenKey,
  CreateWalletStackScreenKey,
  HomeStackScreenKey,
  NavigationStackKey,
  PinCodeStackScreenKey,
  RestoreWalletStackScreenKey,
  RezPointStackScreenKey,
};
